### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by ben-eb** [sindresorhus/atom-perfectionist#1]
Feel free to steal any of this:

https://github.com/ben-eb/atom-cssnano/blob/master/spec/cssnano-spec.js

:smile:

**Comment by sindresorhus** [comment]
Thanks, will definitely steal ;)

**Comment by sindresorhus** [comment]
Looks like the testing story is about to improve, so gonna wait on that: https://github.com/atom/atom/pull/8968

**Comment by ben-eb** [comment]
Alright, sounds good to me. :+1:

**Comment by wooorm** [comment]
It’s not perfect yet, Atom isn’t easy to work with, but I just got tap working! I’ll try to release something soon :)

`package.json`:

``` js
{
  // ...
  "atomTestRunner": "./harness.js",
  // ...
}
```

For `test.js`:

``` js
/* global atom */
var test = require('tape');

test('testing atom', function (t) {
  t.plan(3);

  console.log('It works!');

  t.ok('loadTime' in atom, '`atom` should have a `loadTime` prop');
  t.equal(typeof atom.loadTime, 'number', '`loadTime` should be a number');
  t.ok(atom.loadTime < 1000, '`loadTime` should be less than a second');
});
```

Yields:

<img width="970" alt="screen shot 2016-08-03 at 15 55 05" src="https://cloud.githubusercontent.com/assets/944406/17368036/bff0dc1c-5992-11e6-9f9d-c04afa876ad8.png">
