### ISSUE TITLE
Add support for SCSS

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/atom-perfectionist#2]
https://github.com/ben-eb/perfectionist/issues/15

**Comment by RobbieTheWagner** [comment]
It seems like SCSS works fine for me. What is not working?

**Comment by sindresorhus** [comment]
Does it work just out of the box? From looking at the implementation it seems we would have to pass the `syntax` option to Perfectionist: https://github.com/ben-eb/perfectionist/commit/9571fe70dd35e6ac1c58288474cc80179e400c7b

This is how I did SCSS support in `atom-autoprefixer`: https://github.com/sindresorhus/atom-autoprefixer/blob/99bac7cf2f44a41dc552143441240e4c4a4cf9b5/index.js#L17-L22 Pretty much just use the SCSS parser unless the file is `.css`. That makes it work for SCSS on unsaved buffers too.

// @ben-eb

**Comment by ben-eb** [comment]
Out of the box, perfectionist uses the standard PostCSS parser, so you should use the `syntax` option if you want to _also_ parse single-line comments. The SCSS parser is bundled with perfectionist so you don't have to explicitly depend on it here.
