### ISSUE TITLE
Support for configurability

### ISSUE THREAD

**Issue by itsjustmath** [sindresorhus/atom-perfectionist#3]
Is there currently any [configurability](https://github.com/ben-eb/perfectionist#perfectionistprocesscss-options) for the plugin?

**Comment by sindresorhus** [comment]
Yes, it's in the preferences, like any other Atom plugin.

**Comment by itsjustmath** [comment]
Ugh, sorry to waste your time. I wasn't seeing the settings toggle for some reason.
