### ISSUE TITLE
Run on save

### ISSUE THREAD

**Issue by RobbieTheWagner** [sindresorhus/atom-perfectionist#5]
Would like to be able to have this run on save

**Comment by sindresorhus** [comment]
I'm definitely open to adding this, but don't really have time to implement this myself right now.

Should be pretty easy though, so pull request welcome :)

See how it was implemented in `atom-esformatter`: https://github.com/sindresorhus/atom-esformatter/blob/b7eee38f1c51a0a4cbb96c0cb79862a72746def9/index.js#L49-L65
