### ISSUE TITLE
Indent with tabs

### ISSUE THREAD

**Issue by nessthehero** [sindresorhus/atom-perfectionist#8]
Currently you can only indent with spaces. Can you add an option to use tabs?

**Comment by nessthehero** [comment]
Sorry, didn't see the line about the output issue tracker.

**Comment by sindresorhus** [comment]
Actually, it's correct here. Just need to support the Perfectionist option. I'll add it tomorrow.

**Comment by nessthehero** [comment]
Ah great, I was just about to reopen. Thanks!!
