### ISSUE TITLE
TextEditor.get is deprecated.

### ISSUE THREAD

**Issue by AppDevGuy** [sindresorhus/atom-perfectionist#9]
`TextEditor.prototype.displayBuffer` has always been private, but now
it is gone. Reading the `displayBuffer` property now returns a reference
to the containing `TextEditor`, which now provides *some* of the API of
the defunct `DisplayBuffer` class.
```
TextEditor.get (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:105:14)
<unknown> (.atom/packages/perfectionist/index.js:44:76)
```

ATOM created the above content (quite conveniently) and I am not sure whether this library is still being maintained, but thought I would raise the issue. Kind regards

**Comment by sindresorhus** [comment]
This was already fixed more than a month ago: https://github.com/sindresorhus/atom-perfectionist/commit/58c19e87fe3d2e4fdd7e8facf14c7438ffb9e543
